# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

min_set_cover_cpp <- function(mi, mj, mv, n, d, s) {
    .Call(`_gcrules_glpk_min_set_cover_cpp`, mi, mj, mv, n, d, s)
}

